### ISSUE TITLE
how to use PS Toolkit

### ISSUE THREAD

**Issue by danbromberg** [ns319/PS_toolkit#1]
I'm new to GitHub and Powershell so forgive this very basic question:
This PS Toolkit looks interesting, but I see no download button for me to run it on my PC.
How do I do that?
Thanks,
Dan

**Comment by ns319** [comment]
I don't think you can download it, but you can clone it or just copy the text into your own PS1 file.

**Comment by ns319** [comment]
My mistake, you can download it as a ZIP file from the main page.

**Comment by danbromberg** [comment]
By 'the main page', do you mean:
 https://www.reddit.com/r/PowerShell/comments/uxn773/a_few_days_ago_someone_mentioned_the_old_reset/
OR
 https://github.com/ns319/PS_toolkit

I'm sure it's staring me in the face but I still don't see a download button for a zip file as you indicated.

Thanks for your reply,
Dan

**Comment by ns319** [comment]
https://github.com/ns319/PS_toolkit
Click the green 'Code' button and it's there

**Comment by danbromberg** [comment]
Like I said: "staring me in the face!"
Thanks for the tip, ns319.
Dan
